INSERT INTO currencies (created_at, modified_at, code, iso_code, description, active, scale, symbol)
VALUES
    (NOW(), NULL, 'AUD', 36, 'Австралийский доллар', true, 2, '$'),
    (NOW(), NULL, 'AZN', 944, 'Азербайджанский манат', true, 2, '₼'),
    (NOW(), NULL, 'GBP', 826, 'Фунт стерлингов', true, 2, '£'),
    (NOW(), NULL, 'AMD', 51, 'Армянских драмов', true, 0, NULL),
    (NOW(), NULL, 'BYN', 933, 'Белорусский рубль', true, 2, 'Br'),
    (NOW(), NULL, 'BGN', 975, 'Болгарский лев', true, 2, 'лв'),
    (NOW(), NULL, 'BRL', 986, 'Бразильский реал', true, 2, 'R$'),
    (NOW(), NULL, 'HUF', 348, 'Форинтов', true, 0, 'Ft'),
    (NOW(), NULL, 'VND', 704, 'Донгов', true, 0, '₫'),
    (NOW(), NULL, 'HKD', 344, 'Гонконгский доллар', true, 2, '$'),
    (NOW(), NULL, 'GEL', 981, 'Лари', true, 2, '₾'),
    (NOW(), NULL, 'DKK', 208, 'Датская крона', true, 2, 'kr'),
    (NOW(), NULL, 'AED', 784, 'Дирхам ОАЭ', true, 2, 'د.إ'),
    (NOW(), NULL, 'USD', 840, 'Доллар США', true, 2, '$'),
    (NOW(), NULL, 'EUR', 978, 'Евро', true, 2, '€'),
    (NOW(), NULL, 'EGP', 818, 'Египетских фунтов', true, 0, '£'),
    (NOW(), NULL, 'INR', 356, 'Индийских рупий', true, 0, '₹'),
    (NOW(), NULL, 'IDR', 360, 'Рупий', true, 0, 'Rp'),
    (NOW(), NULL, 'KZT', 398, 'Тенге', true, 0, '₸'),
    (NOW(), NULL, 'CAD', 124, 'Канадский доллар', true, 2, '$'),
    (NOW(), NULL, 'QAR', 634, 'Катарский риал', true, 2, '﷼'),
    (NOW(), NULL, 'KGS', 417, 'Сомов', true, 0, 'с'),
    (NOW(), NULL, 'CNY', 156, 'Юань', true, 2, '¥'),
    (NOW(), NULL, 'MDL', 498, 'Молдавских леев', true, 0, 'L'),
    (NOW(), NULL, 'NZD', 554, 'Новозеландский доллар', true, 2, '$'),
    (NOW(), NULL, 'NOK', 578, 'Норвежских крон', true, 0, 'kr'),
    (NOW(), NULL, 'PLN', 985, 'Злотый', true, 2, 'zł'),
    (NOW(), NULL, 'RON', 946, 'Румынский лей', true, 2, 'lei'),
    (NOW(), NULL, 'XDR', 960, 'СДР (специальные права заимствования)', true, 2, NULL),
    (NOW(), NULL, 'SGD', 702, 'Сингапурский доллар', true, 2, '$'),
    (NOW(), NULL, 'TJS', 972, 'Сомони', true, 0, 'ЅМ'),
    (NOW(), NULL, 'THB', 764, 'Батов', true, 0, '฿'),
    (NOW(), NULL, 'TRY', 949, 'Турецких лир', true, 0, '₺'),
    (NOW(), NULL, 'TMT', 934, 'Новый туркменский манат', true, 2, 'm'),
    (NOW(), NULL, 'UZS', 860, 'Узбекских сумов', true, 0, 'сўм'),
    (NOW(), NULL, 'UAH', 980, 'Гривен', true, 0, '₴'),
    (NOW(), NULL, 'CZK', 203, 'Чешских крон', true, 0, 'Kč'),
    (NOW(), NULL, 'SEK', 752, 'Шведских крон', true, 0, 'kr'),
    (NOW(), NULL, 'CHF', 756, 'Швейцарский франк', true, 2, 'Fr'),
    (NOW(), NULL, 'RSD', 941, 'Сербских динаров', true, 0, 'дин'),
    (NOW(), NULL, 'ZAR', 710, 'Рэндов', true, 0, 'R'),
    (NOW(), NULL, 'KRW', 410, 'Вон', true, 0, '₩'),
    (NOW(), NULL, 'JPY', 392, 'Иен', true, 0, '¥');